### ISSUE TITLE
Preserving correct call in foo.data.frame()

### ISSUE THREAD

**Issue by joranE** [drsimonj/twidlr#10]
I've run into some issues with the default way you've laid out to write the data.frame S3 method. For instance, `MASS::lda`:

    lda.data.frame <- function(data, formula, ...) {
      MASS::lda(formula = formula, data = data, ...)
    }

results in the call being stored in the resulting model object as simply:

    lda(formula = formula, data = data)

which causes `predict` to fail. This seems to happen sometimes, but not always, depending on how the various formula and predict methods were written. I seem to be able to fix it by doing this instead:

    lda.data.frame <- function(data, formula, ...) {
      cl <- as.call(c(quote(MASS:::lda.formula),as.list(match.call())[-1]))
      eval(cl)
    }

in which case the resulting call carried with the model object is the more sensible,

    lda(formula = Species ~ ., data = iris)

and `predict` works as expected.

Do you think this is a better approach to take globally, or do you think there are other problems with this approach?

**Comment by drsimonj** [comment]
I'm not sure of potential problems, but it seems like a good approach and worth exploring!

Aside, perhaps the lazyeval package could be of use here. e.g., take out `eval(as.call(...))` as a more general function as follows:

```
eval_fun <- function(.f, args) {
  eval(as.call(c(lazyeval::expr_find(.f), args)))
}

f <- function(data, formula, ...) {
  args <- as.list(match.call())[-1]
  eval_fun(MASS:::lda.formula, args)
}

# example
fit <- f(iris, Species ~ ., prior = c(1,1,1)/3)
predict(fit, iris[1:10,])$class
```

What do you think?

**Comment by drsimonj** [comment]
@joranE I've played with this idea. See [eval_fun](https://github.com/drsimonj/twidlr/blob/master/R/utilities.R#L82-L84), and it's use in two functions: [t.test](https://github.com/drsimonj/twidlr/blob/master/R/twidlr-stats.R#L28) and [xgboost](https://github.com/drsimonj/twidlr/blob/master/R/twidlr-xgboost.R#L27-L40) as test cases. Would this solve the issues you're encountering?

I quite like this idea in general. It passes everything through one more-robust function (making adjustments easier).

**Comment by joranE** [comment]
That seems to work. My only concern with that is that appears to attach an entire raw representation of the data frame to the call, which could become an issue with large data sets. Doing

    eval_fun(pkg::foo,formula = formula, data = substitute(data),...)

seems to alleviate that issue, but again, I'm not sure what the consequences may be in more complex evaluation situations.

**Comment by drsimonj** [comment]
Quite right. And `substitute` may deal with `data`, but the same issue will carry to all other args in `...`

Perhaps the change can be made in `eval_fun` to better match your original solution:

```
eval_fun <- function(.f, ...) {
  args <- as.list(match.call())[-1]
  eval(as.call(args))
}
```

**Comment by drsimonj** [comment]
Quite right. And `substitute` may deal with `data`, but the same issue will carry to all other args in `...`

I'm trying to think of an alternative approach, but still using `eval_fun`

**Comment by drsimonj** [comment]
OK, what if `eval_fun` were:

```
eval_fun <- function(.f, data = NULL) lazyeval::f_eval(lazyeval::f_unwrap(.f), data = data)
```

This requires that a call be defined as a formula and passed to eval_fun.

Functions for which `data` can be passed "as is" would take a form like:

```
ld <- function(data, formula, ...) {
  .f <- ~ MASS:::lda.formula(formula = formula, data = data, ...)
  eval_fun(.f)
}

# example
ld(iris, Species ~ .)
ld(iris, Species ~ .)$call
predict(ld(iris, Species ~ .))$class
```

Functions where `data` must be munged would take a little extra, and take a form like:

```
xg <- function(data, formula, ...) {
  xy <- twidlr::model_as_xy(data, formula)
  .f <- ~ xgboost::xgboost(data = x, label = y, ...)
  eval_fun(.f, list(x = xy$x, y = xy$y))
}

# example
xg(iris, Species ~ ., nrounds = 5, save_period = FALSE)
```

**Comment by drsimonj** [comment]
After playing with these ideas, it seems the root of the problem lies with `predict` specified by MASS. Unlike `stats::lm`, `MASS::lda` does not store the original data frame for later use. Instead, it searches for the named data frame in the global environment!

To demonstrate, fit `lda` to a data set. `predict` works as expected at first. However, by manipulating, or removing the data set from the global environment, you change the output of predict. Reproducible code:

```r
d <- iris[c(1:5, 51:55, 101:105),]

fit <- MASS::lda(Species ~ ., d)
predict(fit)$class
#>  [1] setosa     setosa     setosa     setosa     setosa     versicolor
#>  [7] versicolor versicolor versicolor versicolor virginica  virginica 
#> [13] virginica  virginica  virginica 
#> Levels: setosa versicolor virginica

d <- d[1:3, ]
predict(fit)$class
#> [1] setosa setosa setosa
#> Levels: setosa versicolor virginica

rm(d)
predict(fit)$class
## Error in is.data.frame(data) : object 'd' not found
```

**This is a broadly important issue**: `predict` may be an "impure" function, such that its output may not always be the same given the same input. 

I see two solutions to this problem:

1. In twidlr's wrapper for predict functions, make `data` mandatory.
2. For models which are associated with an impure `predict`, store `data` at fit time for later use.

My preference is to go with option 1. It's more explicit and doesn't chew up extra memory. Open to thoughts.

**Comment by drsimonj** [comment]
As a record, here's another incident where the default `predict` fails to produce expected results. This comes from the lme4 package, where `predict` on a fitted object does not match the original data set. It does, however, when the original data is explicitly included as `newdata`:

```r
d <- datasets::airquality
nrow(d)
#> [1] 153

fit <- lme4::lmer(Ozone ~ Wind + (Wind | Month), d)

length(lme4:::predict.merMod(fit))
#> [1] 116

length(lme4:::predict.merMod(fit, newdata = d))
#> [1] 153
```

**Comment by drsimonj** [comment]
As a record, I've begun a gist containing any issues of these sorts I find with model and predict functions:
https://gist.github.com/drsimonj/5b2cfc428fce350676db5dc77c059052.js
